Make `getFlamFromCache` method public
thomaspoignant/go-feature-flag pull request #253
Opened 2022-06-10 13:54 UTC by marcosnils

This allows retrieving flag cache metadata like version, rule etc
so the application can use it for visibility purposes. i.e: you want to
know what version of a specific flag your `ffclient` is currently using

2022-06-13 21:25 UTC, marcosnils commented
@thomaspoignant WDYT now?

2022-06-20 10:11 UTC, thomaspoignant requested changes
This looks good to me, except that we are missing the static function when using the `Init` function to initialize `go-feature-flag`.

I am also asking myself about the naming `GetFlagsFromCache()` is not super explicit for someone that has never seen the internal of the SDK.

The only name that comes to my mind is `GetFlagsConfiguration()` but I am not 100% sure if it is more understandable. WDYT?

2022-06-20 10:11 UTC, thomaspoignant commented on variation.go
> +func (g *GoFeatureFlag) GetFlagsFromCache() (map[string]flag.Flag, error) {
Could you also expose `GetFlagsFromCache()` when using the static version of `go-feature-flag`.

As you can see with other functions, we expose them statically and within the `GoFeatureFlag` struct, you can look at `JSONVariation` for the example.

2022-06-20 14:09 UTC, marcosnils commented
Hey Thomas! thx  for taking the time to review.

> This looks good to me, except that we are missing the static function when using the `Init` function to initialize `go-feature-flag`.

Not sure what you mean we are missing here.



> I am also asking myself about the naming `GetFlagsFromCache()` is not super explicit for someone that has never seen the internal of the SDK.
> 
> The only name that comes to my mind is `GetFlagsConfiguration()` but I am not 100% sure if it is more understandable. WDYT?

I personally don't see any problems in exposing internals of the library in the function name. In fact, in this case I believe it's better because it's important for the user to understand that this flag configs are coming from the cache and that you could get outdated information if the poll interval still hasn't triggered.

2022-06-20 14:15 UTC, thomaspoignant commented
> Not sure what you mean we are missing here.

You have 2 ways to use the SDK, you can have a unique and [static initialization](https://github.com/thomaspoignant/go-feature-flag/blob/main/README.md#getting-started) or you can decide to have[ multiple instance of the SDK](https://github.com/thomaspoignant/go-feature-flag/blob/main/docs/configuration.md#multiple-configuration-flag-files).

It also means that we have 2 different levels for the same function.

If you look at `JSONVariation` for example we have 2 different signatures
- https://github.com/thomaspoignant/go-feature-flag/blob/1a486bfacd0bfd5ba1f279e765cb28d7a722e733/variation.go#L48
- https://github.com/thomaspoignant/go-feature-flag/blob/1a486bfacd0bfd5ba1f279e765cb28d7a722e733/variation.go#L110

We need something similar for the new function.



> I personally don't see any problems in exposing internals of the library in the function name. In fact, in this case I believe it's better because it's important for the user to understand that this flag configs are coming from the cache and that you could get outdated information if the poll interval still hasn't triggered.

You convince me about the naming we can keep `GetFlagsFromCache()`.

2022-06-20 14:17 UTC, marcosnils commented
> You have 2 ways to use the SDK, you can have a unique and [static initialization](https://github.com/thomaspoignant/go-feature-flag/blob/main/README.md#getting-started) or you can decide to have[ multiple instance of the SDK](https://github.com/thomaspoignant/go-feature-flag/blob/main/docs/configuration.md#multiple-configuration-flag-files).

gotcha. I'll send the fix in a minute :pray:

2022-06-20 15:16 UTC, thomaspoignant reviewed
I see a lot of changes in the code style, order of import, etc ...
I am not sure this is really needed and it brings noises to your PR.

Do you mind changing only what is needed?
If you prefer I can help with that.

2022-06-20 15:16 UTC, thomaspoignant commented on feature_flag_test.go
> +	_ = ioutil.WriteFile(flagFile.Name(), []byte(updatedFileContent), 0o600)
```suggestion
	_ = ioutil.WriteFile(flagFile.Name(), []byte(updatedFileContent), 0600)
```

2022-06-20 15:16 UTC, thomaspoignant commented on feature_flag_test.go
> +	_ = ioutil.WriteFile(flagFile.Name(), []byte(initialFileContent), 0o600)
```suggestion
	_ = ioutil.WriteFile(flagFile.Name(), []byte(initialFileContent), 0600)
```

2022-06-20 15:16 UTC, thomaspoignant commented on feature_flag_test.go
> +	_ = ioutil.WriteFile(flagFilePath, []byte(initialFileContent), 0o600)
```suggestion
	_ = ioutil.WriteFile(flagFilePath, []byte(initialFileContent), 0600)
```

2022-06-20 15:22 UTC, marcosnils commented
> I see a lot of changes in the code style, order of import, etc ...
> I am not sure this is really needed and it brings noises to your PR.

my vim LSP applied them automatically since I'm using https://github.com/mvdan/gofumpt. Do you still prefer me to revert them? gofumpt is being widely adopted in the Go ecosystem.

2022-06-20 16:24 UTC, thomaspoignant commented
> > I see a lot of changes in the code style, order of import, etc ...
> > I am not sure this is really needed and it brings noises to your PR.
> 
> my vim LSP applied them automatically since I'm using https://github.com/mvdan/gofumpt. Do you still prefer me to revert them? gofumpt is being widely adopted in the Go ecosystem.

no we will keep the change, I will just add `gofumpt` into the configuration of `golangci-lint` for future releases

2022-06-20 16:36 UTC, merged

2022-06-20 16:37 UTC, thomaspoignant commented
@marcosnils thanks a lot for your contribution.
I will release a new version Today with this new feature.

2022-06-20 16:39 UTC, marcosnils commented
sure Thomas! glad to help a tiny bit to make gff great! Please to collaborate with you and thx for the pointers. 

Keep up the awesome work! I know by experience that doing OSS is not an easy task.

2022-06-20 16:57 UTC, thomaspoignant commented
Thank @marcosnils.
I am already in contact with the people at @open-feature, you can find me in the [interested parties](https://github.com/open-feature/community/blob/main/interested-parties.md) list 😉

2022-06-20 17:01 UTC, thomaspoignant commented
Version `v0.24.0` contains this change.