[WIP] Added kinesis exporter and respective tests.
thomaspoignant/go-feature-flag pull request #2575
Opened 2024-10-25 10:59 UTC by baitcode

## Description
Added kinesis exporter and respective tests.

I'm finalising the issue. Need to update documentation and perform manual testing.

## Closes issue(s)
Resolve #2557

## Checklist
- [] I have tested this coded
- [x] I have added unit test to cover this code
- [ ] I have updated the documentation (`README.md` and `/website/docs`)
- [x] I have followed the [contributing guide](CONTRIBUTING.md)

2024-10-25 19:43 UTC, thomaspoignant requested changes
@baitcode thanks a lot for this exporter, this looks really great.
I need to do a proper test using AWS to check that everything goes well but it sounds really good.

There is still a missing part, it is the possibility to configure it in the relay-proxy.
The way to do it is to manage the configuration in this [file](https://github.com/thomaspoignant/go-feature-flag/blob/main/cmd/relayproxy/config/exporter.go).
_If you need help for this I can help._ 

I will do a second review, after setting up a Kinesis on AWS and I let you know how it goes.

One more thing, it is about the comment in the issue about the sharding part, do you think we can let the user configure this when setting up the exporter? 
Ideally we should use the user targetingKey as a sharding key if possible.

2024-10-25 19:43 UTC, thomaspoignant commented on README.md
> +- **AWS S3** *- publish your variation usages to AWS Kinesis Stream.*
```suggestion
- **AWS Kinesis** *- publish your variation usages to AWS Kinesis Stream.*
```

2024-10-28 16:51 UTC, baitcode commented
@thomaspoignant 

I've updated PR. 

I could not figure out `targetingKey`, but, instead, I converted PartitionKey to a function calculating key based on FeatureEvent and Context object. I don't want to get to much deep into details of `targetingKey` implementation. Seems it's being passed through context, but it's goes through all the layers of the application and unfortunately I don't have a capacity to do that research neither I can find doc covering it. Please forget me for that, I would greatly appreciate if you relieved me from that responsibility. Thank you in advance.

2024-10-29 10:53 UTC, baitcode commented
@thomaspoignant do you mind I fix all the linters and Codecoverage?

2024-10-30 07:49 UTC, thomaspoignant commented
> @thomaspoignant do you mind I fix all the linters and Codecoverage?

No please fix it 🙏

2024-10-30 07:54 UTC, thomaspoignant commented on cmd/relayproxy/service/gofeatureflag.go
> +		}, nil
We should maybe add a test for this one.

2024-10-30 07:54 UTC, thomaspoignant commented on exporter/kinesisexporter/exporter.go
> +var DefaultPartitionKey = func(event exporter.FeatureEvent) string {
Proposal to avoid any linter issue
```suggestion
var DefaultPartitionKey = func(_ exporter.FeatureEvent) string {
```

2024-10-30 16:53 UTC, baitcode commented
@thomaspoignant 
As all checks are locked again and I can't see the result of CI execution I used `make coverage` and `make lint` commands to get at least some data. Kinesis is now 85% covered. Added relay case to test list (didn't do much it's coverage is 50% roughly).
I guess that should do the work.

2024-10-31 11:18 UTC, thomaspoignant commented
> @thomaspoignant As all checks are locked again and I can't see the result of CI execution I used `make coverage` and `make lint` commands to get at least some data. Kinesis is now 85% covered. Added relay case to test list (didn't do much it's coverage is 50% roughly). I guess that should do the work.

No worries for that, 85% is really good.

2024-10-31 13:16 UTC, thomaspoignant approved these changes
We are good to go @baitcode.
Thanks a lot for your contribution, I will merge it and it will be part of the next version.

2024-10-31 13:16 UTC, merged