Add Gitlab retriever
thomaspoignant/go-feature-flag pull request #696
Opened 2023-04-17 17:50 UTC by ruairi-wmf

# Description

# Changes include
- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking changes (change that is not backward-compatible and/or changes current functionality)

# Closes issue(s)
Resolve #695

# Checklist
- [X] I have tested this code
- [X] I have added unit test to cover this code
- [ ] I have updated the documentation (`README.md` and `/website/docs`)
- [X] I have followed the [contributing guide](CONTRIBUTING.md)

2023-04-18 09:06 UTC, thomaspoignant requested changes
Hello @ruairi-wmf thanks a lot for your pull request this is an awesome addition to GO Feature Flag.

I have looked at your PR and I have a few things that are not working.
I saw that you are not using the GitLab API to retrieve the files but the public raw access from the website.

From my early investigation, I think it could be great to use the API instead.
This API can help us doing what we want to do: https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository

I've done a quick CURL to test it and it seems to work perfectly.

```shell
curl --header "PRIVATE-TOKEN: <GITLAB TOKEN>" "https://gitlab.com/api/v4/projects/<REPOSITORY SLUG url encoded>/repository/files/<PATH OF YOUR file url encoded>/raw?ref=main"
```

A point of attention is to be sure that you URL encode both the repository slug and the path of your file.
- If your slug is `thomas.poignant/test-go-feature-flag-provider` is should be `thomas.poignant%2Ftest-go-feature-flag-provider` in the URL.
- If your path is `testdata/flags.yaml` it should be `testdata%2Fflags.yaml` in the URL.

2023-04-18 10:35 UTC, ruairi-wmf commented
Thanks Thomas, I'll work on this tonight.  Cheers!

2023-04-19 10:15 UTC, ruairi-wmf commented on retriever/gitlabretriever/retriever.go
> +	// add header for Github Token if specified
Fixed

2023-04-19 10:16 UTC, ruairi-wmf commented on cmd/relayproxy/config/retriever.go
> +	case HTTPRetriever, GitHubRetriever, GitlabRetriever, S3Retriever, FileRetriever, GoogleStorageRetriever, KubernetesRetriever:
Fixed

2023-04-19 10:17 UTC, ruairi-wmf commented on retriever/gitlabretriever/retriever.go
> +	URL := filepath.Join(r.URL, "-raw", branch, r.FilePath)
Fixed

2023-04-20 07:47 UTC, thomaspoignant requested changes
Hey thanks again for the changes, I have left some new comments.
If you need any help or more information let me know.

2023-04-20 07:47 UTC, thomaspoignant commented on cmd/relayproxy/service/gofeatureflag_test.go
> +		{
Can you add another test to validate that it works without setting the branch name?

2023-04-20 07:47 UTC, thomaspoignant commented on retriever/gitlabretriever/retriever.go
> +	}
The variable `branch` is not used.

2023-04-20 07:47 UTC, thomaspoignant commented on retriever/gitlabretriever/retriever.go
> +	reqURL := fmt.Sprintf("%s/api/v4/projects/%s/repository/files/%s/raw?ref=%s", URL, url.QueryEscape(slug), url.QueryEscape(path), r.Branch)
```suggestion
	reqURL := fmt.Sprintf("%s/api/v4/projects/%s/repository/files/%s/raw?ref=%s", URL, url.QueryEscape(slug), url.QueryEscape(path), branch)
```

2023-04-20 07:47 UTC, thomaspoignant commented on retriever/gitlabretriever/retriever.go
> +	}
This is not used, `URL` is re-affected in line 51.

2023-04-20 07:47 UTC, thomaspoignant commented on retriever/gitlabretriever/retriever_test.go
> +		// },
Should we uncomment this?

2023-04-20 07:47 UTC, thomaspoignant commented on retriever/gitlabretriever/retriever.go
> +	URL            string        // https://gitlab.com
If I understand correctly URL is the based DNS of your gitlab instance?
If yes I am not sure if the URL is the right name here.

I would use something like GitlabBaseURL.

WDYT?

2023-04-20 07:47 UTC, thomaspoignant commented on retriever/gitlabretriever/retriever.go
> +	URL = strings.Trim(r.URL, "/")
Would it be better to use `url.Parse` (https://pkg.go.dev/net/url#Parse) and extract the base DNS (`url.Host`) and the scheme (`url.Scheme`).

2023-04-28 13:44 UTC, thomaspoignant commented
Hey @ruairi-wmf I have used your PR to finish it with my remarks.
I will merge it Today and create a new version `1.10.0`, you will be able to use the Gitlab retriever starting this version.

2023-04-28 13:45 UTC, thomaspoignant approved these changes

2023-04-28 14:54 UTC, merged